<div class="loadingio-spinner-rolling-18ciygzclkg">
	<div class="ldio-1ibb5g9mpue">
		<div />
	</div>
</div>

<style type="text/css">
	@keyframes ldio-1ibb5g9mpue {
		0% {
			transform: translate(-50%, -50%) rotate(0deg);
		}
		100% {
			transform: translate(-50%, -50%) rotate(360deg);
		}
	}
	.ldio-1ibb5g9mpue div {
		position: absolute;
		width: 74.4px;
		height: 74.4px;
		border: 12.4px solid #009ef7;
		border-top-color: transparent;
		border-radius: 50%;
	}
	.ldio-1ibb5g9mpue div {
		animation: ldio-1ibb5g9mpue 0.5076142131979695s linear infinite;
		top: 62px;
		left: 62px;
	}
	.loadingio-spinner-rolling-18ciygzclkg {
		width: 124px;
		height: 124px;
		display: inline-block;
		overflow: hidden;
		background: none;
	}
	.ldio-1ibb5g9mpue {
		width: 100%;
		height: 100%;
		position: relative;
		transform: translateZ(0) scale(1);
		backface-visibility: hidden;
		transform-origin: 0 0; /* see note above */
	}
	.ldio-1ibb5g9mpue div {
		box-sizing: content-box;
	}
	/* generated by https://loading.io/ */
</style>
